---
title: "Life Expectancy in Continents over the years"
author: "Mir Afzal"
date: "2023-07-31"
output: pdf
---


```{r}
#| echo:TRUE
#| warning: FALSE

# Install libraries
library(ggplot2)
library(tidyr)
library(gganimate)
theme_set(theme_bw())
library(gapminder)
head(gapminder)

```

# Graph 1: Life Expectancy in Continents over the years
```{r}
## read the gminder data
plot4 = gapminder %>% ggplot(aes(x = gdpPercap, y = lifeExp, size = pop, colour = country)) + ggtitle("Life Expectancy vs GDP per capita by Country") +
  labs(x = "GDP Per Capita",
       y = "Life Expectancy",
       color = "Continent",
       caption = "Source: Hans Rosling's Gapminder Data on Health and Wealth") + geom_point(show.legend = FALSE, alpha = 0.7)

plot4

```

```{r}
plot5 = plot4 +
  #scale_color_viridis_d() 
  scale_color_manual(values = country_colors)+
  scale_size(range = c(2, 12)) +
  scale_x_log10() +
  #labelling
  labs(x = "GDP per capita", y = "Life expectancy")

plot5
```


```{r}
#movement of the time
plot6 = plot5 + transition_time(year) +
    #time frame
  labs(title = "Year: {frame_time}") +
    #shadowing the movement
    shadow_wake(wake_length = 0.1, alpha = FALSE) +
    #marking the shadow
    shadow_mark(alpha = 0.3, size = 0.5) + 
    #making frames
    facet_wrap(~continent) +
    view_follow(fixed_y = TRUE) + 
    ease_aes('linear')

## save
    ## Save into git
  #####plot4.animate
  #### anim_save("gapminder plot9.gif")
```